version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.6

jobs:
  build:
    context: 'tango'
    docker:
      - image: 'circleci/node'
    steps:
    
      - checkout
      - aws-s3/sync:
          from: .
          to: 's3://tangobucket'
          aws-access-key-id: AWS_ACCESS_KEY_ID_BLUE
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_BLUE
          aws-region: AWS_REGION_BLUE
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400" \
            --exclude ".git/*" \
            --exclude ".gitignore" \
            --exclude ".circleci/*" \
          overwrite: true
